version: '3'

services:
  caddy:
    image: caddy:2.3.0
    container_name: caddy_proxy
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    depends_on:
      - app
    env_file: .env_test
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: mxpatlas/devops-for-programmers-project-lvl1:prod
    container_name: nodeos_prod
    #restart: unless-stopped
    #environment: {}
    command: npm test
    depends_on:
      - db
    env_file: .env_test
  db:
    image: postgres:13.2
    container_name: pg_db_nodeos
    restart: always
    env_file: .env_test


