version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: mxpatlas/devops-for-programmers-project-lvl1:prod
    container_name: nodeos_prod
    #restart: unless-stopped
    #env_file: .env
    environment: {}
    command: npm test

