name: tests and docker
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.6'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  docker:
    runs-on: ubuntu-latest
    steps:
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.production
          tags: mxpatlas/devops-for-programmers-project-lvl1:prod
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

