name: tests and docker
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.6'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

